version: "3.9"
services:
  schematic:
    build: .
    container_name: schematic
    entrypoint: python run_api.py
    ports:
      - "3001:3001"
    volumes:
      - .:/work
    working_dir: /work
    environment:
      APP_HOST: "0.0.0.0"
      APP_PORT: "3001"
      SCHEMATIC_CONFIG: /work/config.yml
