openapi: 3.0.0
info:
  title: Schematic REST API
  version: 0.1.0
  description: >-
    This service exposes core functionalities from schematic as REST API
    endpoints

servers:
  - url: /v1

paths:
  /manifest/generate:
    get:
      summary: Endpoint to facilitate manifest generation
      description: Endpoint to create dynamically create metadata manifest files
      parameters:
        - in: query
          name: schema_url
          schema:
            type: string
          description: Data Model URL
          example: >-
            https://raw.githubusercontent.com/Sage-Bionetworks/schematic/develop/tests/data/example.model.jsonld
          required: true
        - in: query
          name: title
          schema:
            type: string
          description: >
            Title of Manifest or Title Prefix, 
            if making multiple manifests
          example: Example
          required: false
        - in: query
          name: data_type
          style: form
          schema:
            type: array
            items: 
              type: string
            nullable: true
          description: >
            Data Model Component(s). 
            To make all manifests, enter "all manifests".
          example: 
            - Patient
            - Biospecimen
          required: true
        - in: query
          name: oauth
          schema:
            type: boolean
            default: true
          description: OAuth or Service Account
          required: false
        - in: query
          name: use_annotations
          schema:
            type: boolean
            default: false
          description: To Use Annotations
          required: false
        - in: query
          name: dataset_id
          schema:
            type: string
            nullable: true
          description: >
            Dataset SynID. Enter 'None' if there is none.
          required: true
      operationId: api.routes.get_manifest_route
      responses:
        "201":
          description: Googlesheet link created
          content:
            application/json:
              schema:
                type: string
      tags:
        - Manifest Operations
  /model/validate:
    post:
      summary: Endpoint to facilitate manifest validation
      description: Endpoint to validate metadata manifest files
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                # csv_file will be the field name in
                # this multipart request
                csv_file:
                  type: string
                  format: binary
      parameters:
        - in: query
          name: schema_url
          schema:
            type: string
          description: Data Model URL
          example: >-
            https://raw.githubusercontent.com/Sage-Bionetworks/schematic/develop/tests/data/example.model.jsonld
          required: true
        - in: query
          name: data_type
          schema:
            type: string
            nullable: true
          description: Data Model Component
          example: Patient
          required: true
      operationId: api.routes.validate_manifest_route
      responses:
        "200":
          description: Manifest Validated
          content:
            application/json:
              schema:
                type: array
                items:
                  type: array
                  items:
                    anyOf:
                      - type: integer
                      - type: string
                      - type: array
                        items:
                          type: string
      tags:
        - Model Operations
  /model/submit:
    post:
      summary: Endpoint to facilitate manifest submission
      description: Endpoint to submit annotated manifest files
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                csv_file:
                  type: string
                  format: binary
      parameters:
        - in: query
          name: schema_url
          schema:
            type: string
          description: Data Model URL
          example: >-
            https://raw.githubusercontent.com/Sage-Bionetworks/schematic/develop/tests/data/example.model.jsonld
          required: true
        - in: query
          name: data_type
          schema:
            type: string
            nullable: true
          description: Data Model Component
          example: Patient
          required: true
        - in: query
          name: dataset_id
          schema:
            type: string
            nullable: true
          description: Dataset SynID
          required: true
      operationId: api.routes.submit_manifest_route
      responses:
        "200":
          description: Manifest submitted
          content:
            application/json:
              schema:
                type: boolean
        "500":
          description: Check schematic log
      tags:
        - Model Operations
  /storage/projects:
    get:
      summary: Get all storage projects the current user has access to
      description: Gets all storage projects the current user has access to, within the scope of the 'storageFileview' attribute.
      operationId: api.routes.get_storage_projects
      parameters:
        - in: query
          name: input_token
          schema:
            type: string
            nullable: false
          description: Token
          example: Token
          required: true
        - in: query
          name: syn_master_file_view
          schema:
            type: string
            nullable: false
          description: synapse ID of master file view. 
          example: syn23643253
          required: true
        - in: query
          name: syn_master_file_name
          schema:
            type: string
            nullable: false
          description: Synapse storage manifest file name. 
          example: synapse_storage_manifest.csv
          required: true
      responses:
        "200":
          description: A list of tuples
        "500":
          description: Check log
      tags:
        - Synapse Storage
  /storage/project/datasets:
    get:
      summary: Gets all datasets in folder under a given storage project that the current user has access to.
      description: Gets all datasets in folder under a given storage project that the current user has access to.
      operationId: api.routes.get_storage_projects_datasets
      parameters:
        - in: query
          name: input_token
          schema:
            type: string
            nullable: false
          description: Token
          example: Token
          required: true
        - in: query
          name: syn_master_file_view
          schema:
            type: string
            nullable: false
          description: synapse ID of master file view. 
          example: syn23643253
          required: true
        - in: query
          name: syn_master_file_name
          schema:
            type: string
            nullable: false
          description: Synapse storage manifest file name. 
          example: synapse_storage_manifest.csv
          required: true
        - in: query
          name: project_id
          schema:
            type: string
            nullable: false
          description: synapse ID of a storage project.
          example: syn26251192
          required: true
      responses:
        "200":
          description: A list of tuples
        "500":
          description: Check log
      tags:
        - Synapse Storage
  /storage/dataset/files:
    get:
      summary: Get all files in a given dataset folder
      description: Get all files in a given dataset folder
      operationId: api.routes.get_files_storage_dataset
      parameters:
        - in: query
          name: input_token
          schema:
            type: string
            nullable: false
          description: Token
          example: Token
          required: true
        - in: query
          name: syn_master_file_view
          schema:
            type: string
            nullable: false
          description: synapse ID of master file view. 
          example: syn23643253
          required: true
        - in: query
          name: syn_master_file_name
          schema:
            type: string
            nullable: false
          description: Synapse storage manifest file name. 
          example: synapse_storage_manifest.csv
          required: true
        - in: query
          name: dataset_id
          schema:
            type: string
            nullable: false
          description: synapse ID of a storage dataset.
          example: syn23643250
          required: true
        - in: query
          name: file_names
          schema:
            type: array
            items:
              type: string
            nullable: true
          description: a list of files with particular names (i.e. Sample_A.txt). If you leave it empty, it will return all dataset files under the dataset ID. 
          required: false
        - in: query
          name: full_path
          schema:
            type: boolean
            nullable: false
          description: if True return the full path as part of this filename; otherwise return just base filename
          required: true
      responses:
        "200":
          description: A list of tuples
        "500":
          description: Check schematic log
      tags:
        - Synapse Storage
  /storage/associateMetadataWithFiles:
    post:
      summary: Associate metadata with files in a storage dataset already on Synapse.
      description: Upload metadataManifest in the storage dataset folder on Synapse as well. Return synapseId of the uploaded manifest file.
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                # csv_file will be the field name in
                # this multipart request
                csv_file:
                  type: string
                  format: binary      
      operationId: api.routes.get_associate_meta_data_with_files
      parameters:
        - in: query
          name: input_token
          schema:
            type: string
            nullable: false
          description: Token
          example: Token
          required: true
        - in: query
          name: syn_master_file_view
          schema:
            type: string
            nullable: false
          description: synapse ID of master file view. 
          example: syn23643253
          required: true
        - in: query
          name: syn_master_file_name
          schema:
            type: string
            nullable: false
          description: Synapse storage manifest file name. 
          example: synapse_storage_manifest.csv
          required: true
        - in: query
          name: dataset_id
          schema:
            type: string
            nullable: false
          description: Dataset SynID
          required: true
        - in: query
          name: use_schema_label
          schema:
            type: boolean
            nullable: false
          example: true
          description: If True, use the schema label. If False, uses the display label from the schema. Attribute display names in the schema must not only include characters that are not accepted by Synapse. 
          required: true
      responses:
        "200":
          description: manifest synapse file ID
        "500":
          description: Check schematic log
      tags:
        - Synapse Storage