name: pdoc

# build the documentation whenever there are new commits on main
on:
  push:
    branches:
      - develop-pydoc
  workflow_dispatch:  # Allow manually triggering the workflow

# security: restrict permissions for CI jobs.
permissions:
  contents: read

concurrency:
  # cancel the current running workflow from the same branch, PR when a new workflow is triggered 
  # when the trigger is not a PR but a push, it will use the commit sha to generate the concurrency group
  # {{ github.workflow }}: the workflow name is used to generate the concurrency group. This allows you to have more than one workflows
  # {{ github.ref_type }}: the type of Git ref object created in the repository. Can be either branch or tag 
  # {{ github.event.pull_request.number}}: get PR number 
  # {{ github.sha }}: full commit sha 
  # credit: https://github.com/Sage-Bionetworks-Workflows/sagetasks/blob/main/.github/workflows/ci.yml
  group: >-
    ${{ github.workflow }}-${{ github.ref_type }}-
    ${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: true
jobs:
  test:

    runson: ubuntu-latest
    env:
      POETRY_VERSION:  1.2.0
    strategy:
      matrix:
        python-version: ["3.7", "3.8", "3.9", "3.10"]

    steps:
      # install poetry 
      - name: Install Poetry Action
        uses: snok/install-poetry@v1.3.2
        virtualenvs-create: true
        virtualenvs-in-project: true
      
      # install dependencies 
      - run: poetry install --no-interaction --no-root
        if: steps.cache-deps.outputs.cache-hit != 'true'

      # create documentation 
      - run: pdoc --docformat google -o docs/api api/routes.py

      - uses: actions/upload-pages-artifact@v1
        with:
          path: docs/api

  # Deploy the artifact to GitHub pages.
  # This is a separate job so that only actions/deploy-pages has the necessary permissions.
  deploy:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - id: deployment
        uses: actions/deploy-pages@v1