# Built from:
# https://docs.github.com/en/actions/guides/building-and-testing-python
# https://github.com/Sage-Bionetworks/challengeutils/blob/master/.github/workflows/pythonapp.yml

name: Test schematic

on: [push, pull_request]

jobs:
  test:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.6, 3.7, 3.8]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install -r test-requirements.txt
        python -m pip install -r requirements.txt
        python -m pip install .
    # Disabling linting until we agree to turn it on
    # - name: Lint with flake8
    #   run: |
    #     # stop the build if there are Python syntax errors or undefined names
    #     flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
    #     # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
    #     flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Test with pytest
      run: |
        pytest --cov=schematic tests/
    # Disabling HTML coverage reports for now
    #   run: |
    #     pytest tests/ --cov=schematic --cov-report=html
    # - name: Upload pytest test results
    #   uses: actions/upload-artifact@v2
    #   with:
    #     name: pytest-results-${{ matrix.python-version }}
    #     path: htmlcov
    #   # Use always() to always run this step to publish test results when there are test failures
    #   if: ${{ always() }}
